<?php
/**
 * Class MemcacheReturnCodes
 * @link http://de2.php.net/manual/de/memcached.getresultcode.php
 */

class MemcacheReturnCodes
{
    const MEMCACHED_SUCCESS = 0;
    const MEMCACHED_FAILURE = 1;
    const MEMCACHED_HOST_LOOKUP_FAILURE  = 2; // getaddrinfo() and getnameinfo() only
    const MEMCACHED_CONNECTION_FAILURE = 3;
    const MEMCACHED_CONNECTION_BIND_FAILURE = 4; // DEPRECATED see MEMCACHED_HOST_LOOKUP_FAILURE
    const MEMCACHED_WRITE_FAILURE = 5;
    const MEMCACHED_READ_FAILURE = 6;
    const MEMCACHED_UNKNOWN_READ_FAILURE = 7;
    const MEMCACHED_PROTOCOL_ERROR = 8;
    const MEMCACHED_CLIENT_ERROR = 9;
    const MEMCACHED_SERVER_ERROR = 10; // Server returns "SERVER_ERROR"
    const MEMCACHED_ERROR  = 11; // Server returns "ERROR"
    const MEMCACHED_CONNECTION_SOCKET_CREATE_FAILURE = 11;
    const MEMCACHED_DATA_EXISTS = 12;
    const MEMCACHED_DATA_DOES_NOT_EXIST = 13;
    const MEMCACHED_NOTSTORED = 14;
    const MEMCACHED_STORED = 15;
    const MEMCACHED_NOTFOUND = 16;
    const MEMCACHED_MEMORY_ALLOCATION_FAILURE = 17;
    const MEMCACHED_PARTIAL_READ = 18;
    const MEMCACHED_SOME_ERRORS = 19;
    const MEMCACHED_NO_SERVERS = 20;
    const MEMCACHED_END = 21;
    const MEMCACHED_DELETED = 22;
    const MEMCACHED_VALUE = 23;
    const MEMCACHED_STAT = 24;
    const MEMCACHED_ITEM = 25;
    const MEMCACHED_ERRNO = 26;
    const MEMCACHED_FAIL_UNIX_SOCKET = 27; // DEPRECATED
    const MEMCACHED_NOT_SUPPORTED = 28;
    const MEMCACHED_NO_KEY_PROVIDED = 29; /* Deprecated. Use MEMCACHED_BAD_KEY_PROVIDED! */
    const MEMCACHED_FETCH_NOTFINISHED = 30;
    const MEMCACHED_TIMEOUT = 31;
    const MEMCACHED_BUFFERED = 32;
    const MEMCACHED_BAD_KEY_PROVIDED = 33;
    const MEMCACHED_INVALID_HOST_PROTOCOL = 34;
    const MEMCACHED_SERVER_MARKED_DEAD = 35;
    const MEMCACHED_UNKNOWN_STAT_KEY = 36;
    const MEMCACHED_E2BIG = 37;
    const MEMCACHED_INVALID_ARGUMENTS = 38;
    const MEMCACHED_KEY_TOO_BIG = 39;
    const MEMCACHED_AUTH_PROBLEM = 40;
    const MEMCACHED_AUTH_FAILURE = 41;
    const MEMCACHED_AUTH_CONTINUE = 42;
    const MEMCACHED_PARSE_ERROR = 43;
    const MEMCACHED_PARSE_USER_ERROR = 44;
    const MEMCACHED_DEPRECATED = 45;
    const MEMCACHED_IN_PROGRESS = 46;
    const MEMCACHED_SERVER_TEMPORARILY_DISABLED = 47;
    const MEMCACHED_SERVER_MEMORY_ALLOCATION_FAILURE = 48;
    const MEMCACHED_MAXIMUM_RETURN = 49; /* Always add new error code before */
}
